return {
	gameinfo_hide = true,
	gamebar_insert = true,
	show_window = true,
	advadv = false,
	start_sound = false,
	calcactive = {
		game = true,
		-- town = true,
		-- industry = false,
		-- line = true,
	},
	gamebar = {
		game = true,
		town = true,
		industry = true,
		-- line = true,
		vehicle = true,
		-- station = true,
		townbuilding = true,
		-- construction = true,
		-- asset = true,
		edge = true,
		person = true,
		-- cargo = true,
	},
}